### ISSUE TITLE
UnboundLocalError: cannot access local variable 'ss' where it is not associated with a value

### ISSUE THREAD

**Issue by fritol** [beatzxbt/bybit-smm#26]
immediately after  python -m main
tried `api` keys with and without quotes
all packages installed fine `pip install -r req...`

using BYBIT feed and exchange
i did not add quotes or removed quotes from param files
what are your exact packages versions?
what python do u use?

```python
Traceback (most recent call last):
  File "/home/ubuntu/bybit-smm/frameworks/sharedstate.py", line 238, in load_parameters
    self.process_parameters(params, reload)
  File "/home/ubuntu/bybit-smm/smm/sharedstate.py", line 35, in process_parameters
    raise e
  File "/home/ubuntu/bybit-smm/smm/sharedstate.py", line 21, in process_parameters
    self.load_exchange(settings["exchange"])
  File "/home/ubuntu/bybit-smm/frameworks/sharedstate.py", line 155, in load_exchange
    self.exchange = Bybit(self.api_key, self.api_secret)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bybit-smm/frameworks/exchange/bybit/exchange.py", line 18, in __init__
    formats=BybitFormats(),
            ^^^^^^^^^^^^^^
  File "/home/ubuntu/bybit-smm/frameworks/exchange/bybit/formats.py", line 17, in __init__
    convert_side=BybitSideConverter(),
                 ^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bybit-smm/frameworks/exchange/bybit/types.py", line 11, in __init__
    super().__init__(BUY="Buy", SELL="Sell")
  File "/home/ubuntu/bybit-smm/frameworks/exchange/base/constants.py", line 99, in __init__
    super().__init__(str_to_int={f"{BUY}": Side.BUY, f"{SELL}": Side.SELL})
TypeError: StrNumConverter.__init__() got an unexpected keyword argument 'str_to_int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/bybit-smm/smm/main.py", line 21, in main
    ss = SmmSharedState(debug=True)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ubuntu/bybit-smm/smm/sharedstate.py", line 11, in __init__
    super().__init__(debug)
  File "/home/ubuntu/bybit-smm/frameworks/sharedstate.py", line 83, in __init__
    self.load_parameters()
  File "/home/ubuntu/bybit-smm/frameworks/sharedstate.py", line 241, in load_parameters
    raise Exception(f"Error loading parameters: {e}")
Exception: Error loading parameters: StrNumConverter.__init__() got an unexpected keyword argument 'str_to_int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ubuntu/bybit-smm/smm/main.py", line 35, in main
    await ss.logging.critical(f"Unexpected exception occurred: {e}")
          ^^
UnboundLocalError: cannot access local variable 'ss' where it is not associated with a value

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ubuntu/bybit-smm/smm/main.py", line 47, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/ubuntu/bybit-smm/smm/main.py", line 39, in main
    await ss.logging.critical("Starting shutdown sequence...")
          ^^
UnboundLocalError: cannot access local variable 'ss' where it is not associated with a value
```

**Comment by beatzxbt** [comment]
tons of stuff still not finished in the alpha version! many core functionalities are still being pushed, but most of it is finished up locally. ill get a working version for bybit/binance up and running by next week if you want to have another go then :)
