### ISSUE TITLE
 Error with bybit private feed: 'topic'

### ISSUE THREAD

**Issue by fritol** [beatzxbt/bybit-smm#27]
ubuntu 24.04 x86  (aws)
python 3.12.3

i had to use different versions of:
```
aiohttp  3.10.2   vs req 3.8.3
PyYAML 6.0.1 vs req 6.0
```
because the required version just always failed to install

[stinkawspiplist.txt.txt](https://github.com/user-attachments/files/16568302/stinkawspiplist.txt.txt)

```
python -m main
2024-08-10 03:15:16.200476: Starting data feeds...
2024-08-10 03:15:18.516656: Connected to ['position', 'order'] bybit feeds...
2024-08-10 03:15:19.169115: Connected to ['orderbook.500.ETHUSDT', 'orderbook.1.ETHUSDT', 'publicTrade.ETHUSDT', 'tickers.ETHUSDT', 'kline.1.ETHUSDT'] bybit feeds...
2024-08-10 03:15:19.223623: Error with bybit private feed: 'topic'
Critical exception occured: 'topic'
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/home/ubuntu/stable/bybit-smm/main.py", line 28, in <module>
    asyncio.run(main())
  File "/usr/lib/python3.12/asyncio/runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/asyncio/runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/ubuntu/stable/bybit-smm/main.py", line 24, in main
    raise e
  File "/home/ubuntu/stable/bybit-smm/main.py", line 16, in main
    await asyncio.gather(
  File "/home/ubuntu/stable/bybit-smm/src/strategy/core.py", line 89, in run
    await asyncio.gather(
  File "/home/ubuntu/stable/bybit-smm/src/strategy/core.py", line 38, in start_feeds
    await asyncio.gather(*tasks)
  File "/home/ubuntu/stable/bybit-smm/src/strategy/ws_feeds/bybitprivatedata.py", line 118, in start_feed
    await asyncio.gather(
  File "/home/ubuntu/stable/bybit-smm/src/strategy/ws_feeds/bybitprivatedata.py", line 112, in _stream_
    raise e
  File "/home/ubuntu/stable/bybit-smm/src/strategy/ws_feeds/bybitprivatedata.py", line 102, in _stream_
    handler = self.topic_handler_map.get(recv["topic"])
                                         ~~~~^^^^^^^^^
KeyError: 'topic'
Unclosed client session
client_session: <aiohttp.client.ClientSession object at 0x7efb3347bc80>
```

**Comment by fritol** [comment]
SOLUTION 
switch to 3.11
install also pyyaml (missing from requirements.txt)
and we cooking!

**Comment by fritol** [comment]
SOLUTION
switch to 3.11
install also pyyaml (missing from requirements.txt)
and we cooking!
